data_file_path: 'dataset\combined_data.csv'
plot_output_directory: 'eda_plots/'

# --- Analysis Thresholds ---
# THIS SECTION IS REQUIRED AND WAS CAUSING THE ERROR.
# It must not be indented.
analysis_thresholds:
  # Ignore columns with more than 60% missing data.
  missing_value: 0.60

# --- Relationship Plots ---
relationship_plots:
  enable_pairplot: true
  
  # Use your key numerical columns here.
  pairplot_features: ['mprival', 'weight', 'revlvl']

# --- General Plotting Preferences ---
plot_style: 'seaborn-v0_8-whitegrid'