# config_automate.yaml

# --- File Paths ---
files:
  input_file: 'dataset\combined_data.csv'
  output_file: 'final_processed_data.csv'

# --- Automation Rules ---
processing_rules:
  # Automatically drop any column with more than 60% missing data.
  missing_value_threshold: 0.60

# --- Logical Column Renaming ---
# Map from the original (cleaned) column name to a new, logical name.
# The script will only rename columns that exist AFTER the dropping step.
column_rename_map:
  mat_description: material_id
  chngd_by: changed_by_user
  chngd_on: change_code
  objecttype: object_type
  crcy: currency_code
  mprival: material_price
  ecn: is_engineering_change
  plnt: plant_code
  revlvl: revision_level
  pgrp: purchasing_group
  technical_object: technical_object_id
  created_on: created_on_date
  acquisition_value: acquisition_value
  weight: weight
  equipment: equipment_id

# --- Data Type and Transformation Rules ---
# Define which operations to apply to the NEWLY RENAMED columns.
transformations:
  # These columns will be converted to the 'category' data type for efficiency.
  force_as_category:
    - is_engineering_change
    - object_type
    - plant_code
    - purchasing_group

  # These heavily skewed columns will get a log transformation.
  apply_log_transform:
    - material_price
    - weight
    - acquisition_value

  # This column will be converted to datetime and engineered.
  engineer_from_date:
    - created_on_date